### ISSUE TITLE
MLFlow manifest appears to be missing

### ISSUE THREAD

**Issue by ChristopherEdwards** [sachua/kubeflow-easy-deploy#3]
The Kustomize config `kfctl_k8s_istio_mlflow.v1.0.2.yaml` appears to refer to a mlflow manifest that doesn't appear to be in the repository.

**Comment by sachua** [comment]
@ChristopherEdwards Hi, you can find the manifest here: https://github.com/sachua/kubeflow-manifests/tree/master/mlflow
